# Intenciones de accion
"""intenciones = [
    ("Hola, ¿cómo estás?", "saludo"),
    ("Buenos días, ¿qué tal?", "saludo"),
    ("Hola, ¿cómo va todo?", "saludo"),
    ("¡Hola! ¿Cómo te encuentras?", "saludo"),
    ("Hola, buen día.", "saludo"),
    ("Saludos, ¿qué noticias?", "saludo"),
    ("Hola, ¿qué hay de nuevo?", "saludo"),
    ("Hey, ¿cómo va?", "saludo"),
    ("¡Hola a todos!", "saludo"),
    ("Hola, ¿cómo va la vida?", "saludo"),
    ("Buenas tardes, ¿qué haces?", "saludo"),
    ("Hola, ¿qué cuentas?", "saludo"),
    ("Saludos cordiales.", "saludo"),
    ("¡Hola, compañero!", "saludo"),
    ("Hola, ¿qué te trae por aquí?", "saludo"),
    ("¡Buen día! ¿Cómo te sientes?", "saludo"),
    ("Hola, ¿cómo puedo ayudarte hoy?", "saludo"),
    ("Hola, ¿qué te trae por acá?", "saludo"),
    ("Hola, ¿en qué puedo servirte?", "saludo"),
    ("Adiós, nos vemos luego.", "despedida"),
    ("Hasta la próxima, amigo.", "despedida"),
    ("Me retiro, ¡hasta luego!", "despedida"),
    ("Adiós, que tengas un buen día.", "despedida"),
    ("Nos vemos más tarde.", "despedida"),
    ("Hasta pronto, cuídate.", "despedida"),
    ("Me despido por ahora.", "despedida"),
    ("Bueno, hasta la próxima.", "despedida"),
    ("Que tengas un buen día, adiós.", "despedida"),
    ("Nos hablamos después.", "despedida"),
    ("Hasta la próxima ocasión.", "despedida"),
    ("Me retiro, adiós.", "despedida"),
    ("Adiós, que tengas una excelente jornada.", "despedida"),
    ("Cerrando sesión, hasta luego.", "despedida"),
    ("Nos vemos pronto, adiós.", "despedida"),
    ("Me despido por ahora, hasta la vista.", "despedida"),
    ("Adiós, cuídate mucho.", "despedida"),
    ("Que tengas un buen descanso, adiós.", "despedida"),
    ("Nos vemos en otra ocasión.", "despedida"),
    ("Mi nombre es Juan.", "informacion_personal"),
    ("Tengo 25 años.", "informacion_personal"),
    ("Soy de Madrid, España.", "informacion_personal"),
    ("Vivo en Nueva York.", "informacion_personal"),
    ("Trabajo como ingeniero de software.", "informacion_personal"),
    ("Soy estudiante de medicina.", "informacion_personal"),
    ("Nací el 15 de marzo de 1990.", "informacion_personal"),
    ("Estudié en la Universidad de Harvard.", "informacion_personal"),
    ("Tengo un perro llamado Fido.", "informacion_personal"),
    ("Hablo tres idiomas: inglés, español y francés.", "informacion_personal"),
    ("Soy vegetariano desde hace cinco años.", "informacion_personal"),
    ("Estoy casado y tengo dos hijos.", "informacion_personal"),
    ("Soy apasionado por la fotografía.", "informacion_personal"),
    ("He viajado por más de 15 países.", "informacion_personal"),
    ("Me encanta el senderismo y la naturaleza.", "informacion_personal"),
    ("Soy fanático de los deportes extremos.", "informacion_personal"),
    ("Tengo una hermana menor llamada Laura.", "informacion_personal"),
    ("Soy un ferviente seguidor de la ciencia ficción.", "informacion_personal"),
    ("Soy un apasionado de la cocina gourmet.", "informacion_personal"),
    ("Gracias por tu ayuda.", "agradecimiento"),
    ("Te agradezco mucho.", "agradecimiento"),
    ("¡Mil gracias!", "agradecimiento"),
    ("Estoy muy agradecido.", "agradecimiento"),
    ("No sé qué haría sin ti.", "agradecimiento"),
    ("Te estoy muy agradecido.", "agradecimiento"),
    ("Aprecio mucho tu apoyo.", "agradecimiento"),
    ("Te doy las gracias.", "agradecimiento"),
    ("Quiero expresar mi gratitud.", "agradecimiento"),
    ("Estoy agradecido por tu tiempo.", "agradecimiento"),
    ("Gracias por ser tan amable.", "agradecimiento"),
    ("Te agradezco de corazón.", "agradecimiento"),
    ("Estoy en deuda contigo.", "agradecimiento"),
    ("Te estoy agradecido por tu paciencia.", "agradecimiento"),
    ("No puedo agradecerte lo suficiente.", "agradecimiento"),
    ("Tu ayuda significa mucho para mí.", "agradecimiento"),
    ("Eres increíble, gracias.", "agradecimiento"),
    ("Quiero expresar mi reconocimiento.", "agradecimiento"),
    ("No tengo palabras para agradecerte.", "agradecimiento"),
    ("Reproduce mi lista de reproducción favorita.", "comando_accion"),
    ("Apaga las luces de la sala.", "comando_accion"),
    ("Añade leche a la lista de compras.", "comando_accion"),
    ("Envía un correo electrónico a Juan.", "comando_accion"),
    ("Crea un recordatorio para las 3:00 PM.", "comando_accion"),
    ("Enciende la cafetera.", "comando_accion"),
    ("Establece una alarma para las 7:00 AM.", "comando_accion"),
    ("Reproduce la película 'El Padrino'.", "comando_accion"),
    ("Activa el modo silencio en mi teléfono.", "comando_accion"),
    ("Muestra la previsión del tiempo para mañana.", "comando_accion"),
    ("Pon la televisión en el canal 5.", "comando_accion"),
    ("Añade una cita en mi calendario para el viernes.", "comando_accion"),
    ("Llama a mamá.", "comando_accion"),
    ("Abre la puerta del garaje.", "comando_accion"),
    ("Busca restaurantes cercanos.", "comando_accion"),
    ("Dibuja una nota en mi bloc de notas.", "comando_accion"),
    ("Traduce esta frase al francés.", "comando_accion"),
    ("Comparte esta canción en redes sociales.", "comando_accion"),
    ("Abre la página principal del sitio web.", "comando_accion"),
    ("Esta película es realmente buena.", "opinion"),
    ("No me gustó el final del libro.", "opinion"),
    ("Creo que este restaurante tiene la mejor comida.", "opinion"),
    ("Esa canción es increíble.", "opinion"),
    ("Este lugar es mi favorito para vacacionar.", "opinion"),
    ("No me gusta el color de esta habitación.", "opinion"),
    ("El servicio en este hotel es excelente.", "opinion"),
    ("La comida en este restaurante es deliciosa.", "opinion"),
    ("No me gusta el diseño de este sitio web.", "opinion"),
    ("Ese actor es genial en su papel.", "opinion"),
    ("Me encanta esta serie de televisión.", "opinion"),
    ("La música en este concierto fue increíble.", "opinion"),
    ("No recomendaría este producto a nadie.", "opinion"),
    ("Creo que este libro es una obra maestra.", "opinion"),
    ("No me gusta el sabor de esta bebida.", "opinion"),
    ("Este software es fácil de usar.", "opinion"),
    ("Esa exposición de arte fue asombrosa.", "opinion"),
    ("Este coche tiene un buen rendimiento.", "opinion"),
    ("Esta aplicación es muy útil.", "opinion"),
    ("No, gracias, no estoy interesado.", "negacion_rechazo"),
    ("Lo siento, pero no puedo hacer eso.", "negacion_rechazo"),
    ("No estoy de acuerdo con eso.", "negacion_rechazo"),
    ("Prefiero no hacerlo en este momento.", "negacion_rechazo"),
    ("No quiero participar en esa actividad.", "negacion_rechazo"),
    ("No, no estoy dispuesto a hacerlo.", "negacion_rechazo"),
    ("No me siento cómodo con esa idea.", "negacion_rechazo"),
    ("No, eso no encaja con mis planes.", "negacion_rechazo"),
    ("No, no creo que sea una buena idea.", "negacion_rechazo"),
    ("No estoy dispuesto a asumir esa responsabilidad.", "negacion_rechazo"),
    ("No me gustaría hacerlo de esa manera.", "negacion_rechazo"),
    ("Prefiero no comprometerme en este momento.", "negacion_rechazo"),
    ("No creo que sea apropiado en este contexto.", "negacion_rechazo"),
    ("No, eso no funciona para mí.", "negacion_rechazo"),
    ("No, no estoy interesado en esa oferta.", "negacion_rechazo"),
    ("Eso no es lo que estaba buscando.", "negacion_rechazo"),
    ("No, no puedo ayudarte con eso.", "negacion_rechazo"),
    ("No estoy dispuesto a cambiar de opinión.", "negacion_rechazo"),
    ("No, no estoy de acuerdo con esa propuesta.", "negacion_rechazo"),
    ("Sí, eso suena bien.", "confirmacion"),
    ("Estoy de acuerdo contigo.", "confirmacion"),
    ("Sí, quiero hacerlo de esa manera.", "confirmacion"),
    ("Por supuesto, puedes contar conmigo.", "confirmacion"),
    ("Sí, eso es lo que necesito.", "confirmacion"),
    ("Sí, estoy seguro de eso.", "confirmacion"),
    ("Sí, eso es exactamente lo que quiero.", "confirmacion"),
    ("Sí, estoy de acuerdo en seguir adelante.", "confirmacion"),
    ("Sí, eso suena como la elección correcta.", "confirmacion"),
    ("Sí, estoy listo para continuar.", "confirmacion"),
    ("Sí, estoy seguro de mi decisión.", "confirmacion"),
    ("Sí, eso es lo que tenía en mente.", "confirmacion"),
    ("Sí, eso es exactamente lo que te pedí.", "confirmacion"),
    ("Sí, eso es lo que esperaba.", "confirmacion"),
    ("Sí, puedes proceder de esa manera.", "confirmacion"),
    ("Sí, eso es lo que estaba buscando.", "confirmacion"),
    ("Sí, eso es lo que necesito ahora.", "confirmacion"),
    ("Sí, estoy de acuerdo en hacerlo así.", "confirmacion"),
    ("Sí, eso es correcto.", "confirmacion"),
    ("¿Cómo estás hoy?", "pregunta_general"),
    ("¿Qué has estado haciendo recientemente?", "pregunta_general"),
    ("¿Cómo funcionas?", "pregunta_general"),
    ("¿Puedes hablar otros idiomas?", "pregunta_general"),
    ("¿Cuál es tu nombre?", "pregunta_general"),
    ("¿Cómo puedo contactarte?", "pregunta_general"),
    ("¿Cuál es tu función principal?", "pregunta_general"),
    ("¿Puedes decirme un chiste?", "pregunta_general"),
    ("¿Tienes alguna recomendación para mí?", "pregunta_general"),
    ("¿Qué te gusta hacer en tu tiempo libre?", "pregunta_general"),
    ("¿Puedes contarme un hecho interesante?", "pregunta_general"),
    ("¿Dónde estás ubicado?", "pregunta_general"),
    ("¿Cómo puedo mejorar mi productividad?", "pregunta_general"),
    ("¿Cuál es tu capacidad de aprendizaje?", "pregunta_general"),
    ("¿Qué puedes hacer por mí?", "pregunta_general"),
    ("¿Cuál es tu objetivo principal?", "pregunta_general"),
    ("¿Cuántos años tienes?", "pregunta_general"),
    ("¿Cuál es tu programación?", "pregunta_general"),
    ("¿Puedes darme un consejo?", "pregunta_general"),
]"""
INTENCIONES = {
    "pregunta": ["qué", "cómo", "por qué", "cuándo", "dónde", "quién", "cuál", "pregunta"],
    "comando": ["abre", "reproduce", "enciende", "apaga", "bloquea", "busca", "inicia"],
    "saludo": ["hola", "buen día", "qué tal", "buenas tardes"],
    "despedida": ["chau", "adiós", "hasta luego", "nos vemos"],
    "alago": ["gracias", "muy bien", "me gusta", "eres genial", "qué bueno", "excelente"]
}

preguntas = {
    "¿Quién eres?": ["quién eres", "quien eres", "quien sos", "quién sos", "vos quien sos", "tu quien eres"],
    "¿Qué puedes hacer?": ["qué sabes hacer", "cuáles son tus habilidades", "qué funciones tienes"],
    "Escuchar música": ["quiero escuchar música", "reproducir una canción", "lista de reproducción"],
    "Queen": ["queen", "cuin", "kuin"],
    "Volumen": ["subir volumen", "bajar volumen", "ajustar volumen", "volúmen", "Subir volumen"],
    "Apagar": ["apagar la computadora", "apagar windows", "cerrar el sistema"],
    "Alago": ["Que linda oficina", "Muy linda oficina", "Está buena la oficina"],
    "Equivocado": ["fue un error", "me confundí", "no quería molestarte", "perdón", "perdon me equivoque", "Fue un error", "Me confundí", "No queria molestarte"],
    "Calendario": ["consultar calendario", "qué eventos tengo", "mostrar calendario", "Calendario"],
    "Saludo": ["hola sara", "hola sarah", "sara", "ayúdame sara", "sarah ayudame", "sara estás ahí", "¿sara estas ahi?", "okay sara", "sara necesito tu ayuda"],
    "Despedida": ["chau sara", "adiós sara", "hasta luego", "gracias por tu ayuda", "chau sara, gracias por tu ayuda", "muchas gracias por tu ayuda, hasta mañana", "adiós"],
    "Visitas": ["tenemos visitas", "vinieron a visitarnos", "saluda a nuestros invitados", "saluda a nuestors invitados"],
    "Suspension": ["iniciar protocolo de suspensión", "activar el protocolo de suspensión", "me tengo que retirar", "en breve vuelvo", "en un rato vuelvo"],
    "Bloquear pantalla": ["bloquear pantalla", "necesito que bloquees la pantalla", "pantalla bloqueada"],
    "hola sara": ["hola sarah", "hola sara", "sara", "ayudame sara", "sarah ayudame", "¿sara estas ahi?", "Sara necesito tu ayuda", "okay sara", "sara estas ahí"],
    "Clima": ["¿cómo está el clima?", "qué temperatura hace", "¿va a llover hoy?", "pronóstico del tiempo"],
    "Chistes": ["cuéntame un chiste", "quiero reírme", "dime algo gracioso"],
    "Recordatorios": ["crea un recordatorio", "recuérdame algo", "programar un recordatorio"],
    "Noticias": ["¿qué noticias hay hoy?", "infórmame sobre las noticias", "resumen de noticias"],
    "Hora": ["¿qué hora es?", "dame la hora", "hora actual"],
    "Fecha": ["¿qué día es hoy?", "dame la fecha", "fecha actual"]

    # Agrega más preguntas y variantes aquí "pregunta": ["variable de pregunta"],
}

ACCIONES = {
    "Abrir navegador": ["abre el navegador", "quiero buscar algo", "abre chrome", "abre firefox"],
    "Reproducir música": ["pon música", "quiero escuchar música", "reproduce una canción"],
    "Cerrar sesión": ["cierra la sesión", "quiero cerrar sesión"],
    "Bloquear pantalla": ["bloquea la pantalla", "quiero bloquear la computadora"],
    "Consultar calendario": ["abre el calendario", "quiero ver mis eventos", "consulta mi agenda"],
    "Establecer alarma": ["configura una alarma", "pon una alarma para las 7", "quiero despertarme a las 8"],
    "Apagar computadora": ["apaga la computadora", "quiero apagar el sistema", "apaga windows"],
    "Subir volumen": ["sube el volumen", "quiero escuchar más fuerte"],
    "Bajar volumen": ["baja el volumen", "quiero escuchar más bajo"],
    "Abrir Word": ["abre word", "quiero escribir un documento"],
    "Abrir Excel": ["abre excel", "quiero hacer una tabla"]
}
